### ISSUE TITLE
Couldn't run gradle

### ISSUE THREAD

**Issue by alexnsolo** [forana/KeyBored#11]
C:\Users\Alex\Documents\GitHub\KeyBored>gradle fatjar --stacktrace
The TaskContainer.add() method has been deprecated and is scheduled to be remove
d in Gradle 2.0. Please use the create() method instead.
:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileJava'.
  
  > invalid source release: 1.7
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compile
  Java'.
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecuteActions(ExecuteActionsTaskExecuter.java:69)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecute(ExecuteActionsTaskExecuter.java:46)
      at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
  uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
      at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
  ute(SkipUpToDateTaskExecuter.java:64)
      at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
  e(ValidatingTaskExecuter.java:58)
      at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
  ter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
  .execute(SkipTaskWithNoActionsExecuter.java:52)
      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
  e(SkipOnlyIfTaskExecuter.java:53)
      at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
  .execute(ExecuteAtMostOnceTaskExecuter.java:43)
      at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailur
  e(AbstractTask.java:289)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
  orker.executeTask(AbstractTaskPlanExecutor.java:79)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
  orker.processTask(AbstractTaskPlanExecutor.java:63)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
  orker.run(AbstractTaskPlanExecutor.java:51)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
  tTaskPlanExecutor.java:23)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
  ltTaskGraphExecuter.java:86)
      at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
  ExecutionAction.java:29)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
  r.java:61)
      at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExec
  uter.java:23)
      at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecu
  ter.java:67)
      at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
  ecutionAction.java:32)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
  r.java:61)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
  r.java:54)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
  GradleLauncher.java:166)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
  Launcher.java:113)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
  cher.java:81)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
  troller.run(InProcessBuildActionExecuter.java:64)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
  a:33)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
  a:24)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
  ssBuildActionExecuter.java:35)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
  ssBuildActionExecuter.java:26)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
      at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
  a:171)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
  execute(CommandLineActionFactory.java:201)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
  execute(CommandLineActionFactory.java:174)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
  CommandLineActionFactory.java:170)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
  CommandLineActionFactory.java:139)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
  ortingAction.java:33)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
  ortingAction.java:22)
      at org.gradle.launcher.Main.doAction(Main.java:46)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.Main.main(Main.java:37)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
  trap.java:50)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
  ava:32)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
  Caused by: java.lang.IllegalArgumentException: invalid source release: 1.7
      at com.sun.tools.javac.main.RecognizedOptions$GrumpyHelper.error(Recogni
  zedOptions.java:75)
      at com.sun.tools.javac.main.RecognizedOptions$13.process(RecognizedOptio
  ns.java:370)
      at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:247)
      at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:207)
      at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:53)
      at org.gradle.api.internal.tasks.compile.jdk6.Jdk6JavaCompiler.createCom
  pileTask(Jdk6JavaCompiler.java:62)
      at org.gradle.api.internal.tasks.compile.jdk6.Jdk6JavaCompiler.execute(J
  dk6JavaCompiler.java:44)
      at org.gradle.api.internal.tasks.compile.jdk6.Jdk6JavaCompiler.execute(J
  dk6JavaCompiler.java:38)
      at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegat
  eAndHandleErrors(NormalizingJavaCompiler.java:96)
      at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute
  (NormalizingJavaCompiler.java:49)
      at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute
  (NormalizingJavaCompiler.java:35)
      at org.gradle.api.internal.tasks.compile.DelegatingJavaCompiler.execute(
  DelegatingJavaCompiler.java:29)
      at org.gradle.api.internal.tasks.compile.DelegatingJavaCompiler.execute(
  DelegatingJavaCompiler.java:20)
      at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.exe
  cute(CleaningJavaCompilerSupport.java:33)
      at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.exe
  cute(CleaningJavaCompilerSupport.java:24)
      at org.gradle.api.tasks.compile.Compile.performCompilation(Compile.java:
  165)
      at org.gradle.api.tasks.compile.Compile.compile(Compile.java:153)
      at org.gradle.api.tasks.compile.Compile.compile(Compile.java:87)
      at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  actory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:236)
  
  ```
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  ```
  
  actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  actory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:223)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
  ctTask.java:533)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
  ctTask.java:516)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecuteAction(ExecuteActionsTaskExecuter.java:80)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecuteActions(ExecuteActionsTaskExecuter.java:61)
      ... 43 more

BUILD FAILED

Total time: 2.813 secs

C:\Users\Alex\Documents\GitHub\KeyBored>

**Comment by alexnsolo** [comment]
Worked after I switched to using Java 1.7.0. Whoops.
